autotransform/batcher/chunk.py, autotransform/event/base.py, autotransform/filter/regex.py, autotransform/schema/schema.py, autotransform/transformer/script.py, tests/batcher/test_chunk.py, tests/batcher/test_directory.py, tests/batcher/test_single.py, tests/filter/test_regex.py, tests/input/test_directory.py, tests/input/test_gitgrep.py, tests/item/test_file.py, tests/schema/test_schema.py
Apply Black formatting to all python files with @black_format
=> [AutoTransform][Black Format] Format all python files

CHANGELOG.md, autotransform/manager.json, autotransform/scheduler.json, examples/manager.json, examples/scheduler.json, src/python/autotransform/config/config.py, src/python/autotransform/scripts/commands/initialize.py, src/python/autotransform/util/manager.py, src/python/autotransform/util/scheduler.py, tests/util/data/manager.json, tests/util/data/scheduler.json
See https://github.com/nathro/AutoTransform/issues/53
=> Remove Runner from Manager and Scheduler

CHANGELOG.md, docs/source/autotransform.step.action.request.rst, docs/source/autotransform.step.action.rst, src/python/autotransform/step/action/base.py, src/python/autotransform/step/action/request.py, tests/step/action/test_factory.py
See https://github.com/nathro/AutoTransform/issues/50
Adds an Action for using REST APIs as part of the Manager. Has replacement options for environment variables/change values since you will likely need to include IDs or tokens as part of these requests.
=> Add RequestAction

CHANGELOG.md, setup.py, src/python/autotransform/change/base.py, src/python/autotransform/change/github.py, src/python/autotransform/scripts/migrations/p1_0_5.py, src/python/autotransform/step/condition/base.py, src/python/autotransform/step/condition/state.py, src/python/autotransform/util/github.py, src/python/autotransform/util/manager.py, tests/change/test_github.py, tests/conftest.py, tests/step/condition/test_factory.py, tests/util/data/manager.json, tests/util/test_manager.py
See https://github.com/nathro/AutoTransform/issues/58
=> Add TestState and ReviewState conditions

CHANGELOG.md, docs/source/autotransform.util.enums.rst, docs/source/autotransform.util.rst, setup.py, src/python/autotransform/config/config.py, src/python/autotransform/runner/base.py, src/python/autotransform/runner/jenkins.py, tests/runner/test_factory.py
Also fixes some documentation stuff.
=> Update Jenkins runners to have file runner and API runner

CHANGELOG.md, autotransform/manager.json, src/python/autotransform/scripts/migrations/p1_0_1.py, src/python/autotransform/scripts/migrations/p1_0_3.py, src/python/autotransform/scripts/migrations/p1_0_5.py
https://github.com/nathro/AutoTransform/issues/62
=> Fix migration scripts

.github/workflows/autotransform.run.yml, examples/workflows/autotransform.run.yml
Small fix for how our workflows work for GithubActions.
=> Fix runners to have filter set up properly for handling whitespace

CHANGELOG.md, docs/source/autotransform.step.condition.request.rst, docs/source/autotransform.step.conditional.rst, docs/source/autotransform.util.request.rst, src/python/autotransform/step/action/request.py, src/python/autotransform/step/condition/base.py, src/python/autotransform/step/condition/request.py, src/python/autotransform/util/request.py, tests/step/action/test_factory.py, tests/step/condition/test_factory.py
Extracts the request logic to a util function from RequestAction and uses that logic as the basis for RequestStrCondition, which can be used to get state through a REST API for a change.
=> Update request logic

CHANGELOG.md, docs/source/autotransform.batcher.codeowners.rst, docs/source/autotransform.batcher.rst, requirements.txt, setup.py, src/python/autotransform/batcher/base.py, src/python/autotransform/batcher/codeowners.py, src/python/autotransform/repo/github.py, tests/batcher/test_factory.py
=> Add CodeownersBatcher

src/python/autotransform/step/action/request.py, src/python/autotransform/step/condition/request.py, src/python/autotransform/util/request.py
Some fixes to how requests work to handle non-string values in replacers and support recursive replacement
=> Fix RequestHandler

requirements.txt, src/python/autotransform/batcher/base.py, src/python/autotransform/batcher/codeowners.py, src/python/autotransform/change/base.py, src/python/autotransform/command/base.py, src/python/autotransform/filter/base.py, src/python/autotransform/input/base.py, src/python/autotransform/repo/base.py, src/python/autotransform/runner/base.py, src/python/autotransform/schema/builder.py, src/python/autotransform/step/action/base.py, src/python/autotransform/step/base.py, src/python/autotransform/step/condition/base.py, src/python/autotransform/transformer/base.py, src/python/autotransform/validator/base.py, tests/batcher/test_factory.py, tests/change/test_factory.py, tests/command/test_factory.py, tests/filter/test_factory.py, tests/input/test_factory.py, tests/item/test_factory.py, tests/repo/test_factory.py, tests/runner/test_factory.py, tests/schema/test_factory.py, tests/step/action/test_factory.py, tests/step/condition/test_factory.py, tests/step/test_factory.py, tests/transformer/test_factory.py, tests/validator/test_factory.py
=> Fix issue with CodeownersBatcher using wrong variable

CHANGELOG.md, src/python/autotransform/change/base.py, src/python/autotransform/change/github.py, src/python/autotransform/step/condition/base.py, src/python/autotransform/step/condition/state.py, src/python/autotransform/util/github.py, tests/step/condition/test_factory.py
=> Add MergeableStateCondition

CHANGELOG.md, src/python/autotransform/scripts/commands/manage.py, src/python/autotransform/scripts/commands/schedule.py, src/python/autotransform/step/action/source.py, src/python/autotransform/util/github.py, src/python/autotransform/util/manager.py, src/python/autotransform/util/scheduler.py
Adds the ability to run scheduling and management with local runners.
=> Make Schedule and Manage commands runnable locally

.github/workflows/pylint.yml, .github/workflows/release.yml, src/python/autotransform/util/github.py
Missed a spot where we passed the pull request response in to the PullRequest
=> Fix creation of Pull Requests with new constructor

CHANGELOG.md, src/python/autotransform/config/config.py, src/python/autotransform/util/component.py
Redacting these tokens in reprs
=> Redact token fields in Config

src/python/autotransform/config/config.py
=> Fix the prompt for entering a repo_override for Config

src/python/autotransform/config/environment.py
Fix the EnvironmentConfigFetcher to be able to set repo_override
=> Add environment variable for repo_override in fetcher

src/python/autotransform/config/config.py
=> Fix merge to include repo override

README.md
=> Add tutorial videos to readme

CHANGELOG.md, src/python/autotransform/filter/aggregate.py, src/python/autotransform/filter/base.py, src/python/autotransform/step/condition/aggregate.py, src/python/autotransform/util/enums.py, tests/filter/test_aggregate.py, tests/filter/test_factory.py, tests/step/condition/test_factory.py, tests/step/test_factory.py
Added the AggregateFilter class, mostly done using ChatGPT just to see what using it to write stuff would be like.
=> Add AggregateFilter

CHANGELOG.md, src/python/autotransform/command/script.py, src/python/autotransform/transformer/script.py, src/python/autotransform/util/functions.py, src/python/autotransform/util/request.py, src/python/autotransform/validator/script.py, tests/command/test_script.py, tests/transformer/test_script.py, tests/validator/test_script.py
Makes a bunch of changes to script components and enables using environment variables for replacement.  Also consolidates the script process logic because it's super duplicative right now.
=> Update script components and consolidate proc logic

CHANGELOG.md, src/python/autotransform/batcher/codeowners.py
We need to make sure to add this when the field isn't present
=> Support reviewers in CodeownersBatcher when not present as field

CHANGELOG.md, src/python/autotransform/transformer/script.py, tests/transformer/test_factory.py, tests/transformer/test_script.py
=> Supporting chunking in ScriptTransformer

docs/source/autotransform.filter.aggregate.rst, docs/source/autotransform.filter.codeowners.rst, docs/source/autotransform.filter.rst, docs/source/autotransform.scripts.migrations.p1_0_1.rst, docs/source/autotransform.scripts.migrations.p1_0_3.rst, docs/source/autotransform.scripts.migrations.p1_0_5.rst, docs/source/autotransform.scripts.migrations.rst, docs/source/autotransform.scripts.rst, docs/source/autotransform.util.functions.rst, docs/source/autotransform.util.rst
=> Fix some missing documentation

CHANGELOG.md, docs/source/autotransform.event.rst, docs/source/autotransform.event.verbose.rst, src/python/autotransform/command/script.py, src/python/autotransform/event/handler.py, src/python/autotransform/event/logginglevel.py, src/python/autotransform/event/type.py, src/python/autotransform/event/verbose.py, src/python/autotransform/repo/github.py, src/python/autotransform/runner/github.py, src/python/autotransform/runner/jenkins.py, src/python/autotransform/schema/schema.py, src/python/autotransform/scripts/commands/manage.py, src/python/autotransform/scripts/commands/run.py, src/python/autotransform/scripts/commands/schedule.py, src/python/autotransform/scripts/commands/update.py, src/python/autotransform/transformer/jscodeshift.py, src/python/autotransform/transformer/libcst.py, src/python/autotransform/transformer/script.py, src/python/autotransform/util/functions.py, src/python/autotransform/util/github.py, src/python/autotransform/validator/script.py
The current verbose logs are TOO verbose, so I'm separating out a debug logging setting that's got extreme detail from the verbose logs that are more commonly useful. Also updates some stuff to WarningEvents that should probably be warnings.
=> Update DebugEvent logging to separate verbose and debug logs

CHANGELOG.md, src/python/autotransform/batcher/codeowners.py
=> Add maximum batch size option to CodeownersBatcher

src/python/autotransform/batcher/codeowners.py
num_chunks was used without being set. Also updates usage of index variable.
=> Fix usage of variable before set

CHANGELOG.md, src/python/autotransform/change/github.py, src/python/autotransform/repo/github.py, src/python/autotransform/util/github.py, tests/change/test_github.py
Update to use gists for storing information related to changes.
=> Update automation info to use gist

src/python/autotransform/event/action.py
=> Add the change an action is taken on to the message in logging

CHANGELOG.md, requirements.txt, src/python/autotransform/event/handler.py, src/python/autotransform/util/github.py
Right now a person who leaves a review is no longer considered a reviewer. This fixes that issue.
=> Fix reviewers list for pull request

CHANGELOG.md, src/python/autotransform/command/script.py, src/python/autotransform/config/config.py, src/python/autotransform/filter/aggregate.py, tests/util/test_manager.py, tests/util/test_scheduler.py
Fixes a bug with ScriptCommand when no changes are present and run_on_changes is set to true.
=> Fix ScriptCommand bug

CHANGELOG.md, docs/source/autotransform.input.rst, docs/source/autotransform.input.script.rst, src/python/autotransform/input/base.py, src/python/autotransform/input/script.py, tests/input/test_factory.py
Adds the ScriptInput component to support script based Inputs.
=> Add ScriptInput component

CHANGELOG.md, docs/source/autotransform.filter.rst, docs/source/autotransform.filter.script.rst, src/python/autotransform/filter/base.py, src/python/autotransform/filter/script.py, src/python/autotransform/input/script.py, src/python/autotransform/schema/schema.py, tests/filter/test_factory.py
Adds the ScriptFilter component and the BulkFilter base.
=> ScriptFilter

.github/workflows/autotransform.run.yml, CHANGELOG.md, docs/source/autotransform.transformer.openai.rst, docs/source/autotransform.transformer.rst, requirements.txt, setup.py, src/python/autotransform/config/config.py, src/python/autotransform/config/environment.py, src/python/autotransform/transformer/base.py, src/python/autotransform/transformer/openai.py, tests/transformer/test_factory.py
Adds a Transformer that leverages the OpenAI API for completitions
=> OpenAITransformer

src/python/autotransform/transformer/openai.py, tests/transformer/test_factory.py
Adds Validators to OpenAITransformer that can create a feedback loop to improve the LLM completion.
=> Add Validators to OpenAITransformer

src/python/autotransform/transformer/openai.py, tests/transformer/test_factory.py
Adds a commands param to OpenAITransformer
=> Add commands to OpenAITransformer

src/python/autotransform/transformer/openai.py
- Adds validation for OpenAITransformer params
- Cleans up some code
- Adds comments
- Adds more logging
- Fixes some formatting
- Reverts changes if validators fail on last completion attempt
=> Make some improvements to the OpenAITransformer

src/python/autotransform/batcher/__init__.py, src/python/autotransform/batcher/chunk.py, src/python/autotransform/batcher/codeowners.py, src/python/autotransform/batcher/directory.py, src/python/autotransform/batcher/extradata.py, src/python/autotransform/batcher/regex.py, src/python/autotransform/batcher/single.py
<<<Automation Info Gist: 0a349f194f20c315d0738339aec9018a>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/batcher

src/python/autotransform/step/__init__.py
<<<Automation Info Gist: e6ef980429e64bed8a1366c1759bf2c4>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/step

src/python/autotransform/step/condition/aggregate.py, src/python/autotransform/step/condition/created.py, src/python/autotransform/step/condition/labels.py, src/python/autotransform/step/condition/request.py, src/python/autotransform/step/condition/reviewers.py, src/python/autotransform/step/condition/schema.py, src/python/autotransform/step/condition/state.py, src/python/autotransform/step/condition/updated.py
<<<Automation Info Gist: 5708e1df80d3d820347678c00dc691ba>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/step/condition

src/python/autotransform/step/action/comments.py, src/python/autotransform/step/action/labels.py, src/python/autotransform/step/action/request.py, src/python/autotransform/step/action/reviewers.py
<<<Automation Info Gist: 0f469cb3873c7b1ee20280f6010fb972>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/step/action

src/python/autotransform/repo/base.py, src/python/autotransform/repo/git.py
<<<Automation Info Gist: 12b12f2c23f935db5bdbf918761335c3>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/repo

src/python/autotransform/filter/codeowners.py, src/python/autotransform/filter/key_hash_shard.py, src/python/autotransform/filter/regex.py, src/python/autotransform/filter/script.py
<<<Automation Info Gist: 3027d807de2c1edc5f4dcedabed18fd5>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/filter

src/python/autotransform/change/github.py
<<<Automation Info Gist: 499df09c73b61f38640fa10f30017dc7>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/change

src/python/autotransform/model/openai.py
<<<Automation Info Gist: 5b4e130ec00d368851ddced0906bd079>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/model

src/python/autotransform/command/script.py
<<<Automation Info Gist: b30f776bc56b43e629111432e83bfd51>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/command

src/python/autotransform/transformer/jscodeshift.py, src/python/autotransform/transformer/libcst.py, src/python/autotransform/transformer/regex.py, src/python/autotransform/transformer/script.py, src/python/autotransform/transformer/single.py
<<<Automation Info Gist: 80ee474f3df6b531e62c307025c3c3e1>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/transformer

src/python/autotransform/scripts/main.py
<<<Automation Info Gist: 0ab0e2aee1c0682e515dc12d1fba1c4a>>>
=> [AutoTransform][Crawler] Crawl python files: src/python/autotransform/scripts

src/python/autotransform/model/openai.py
This fixes the OpenAIModel from modifying the messages that are passed to it so that when a retry happens they aren't constantly getting added to.
=> Fix OpenAIModel retry logic

src/python/autotransform/config/config.py, src/python/autotransform/config/environment.py, src/python/autotransform/event/handler.py, src/python/autotransform/util/component.py
Fixes an infinite recursion issue that occurs when custom EventNotifiers are used.
=> Fix infinite recursion with custom event notifiers

autotransform/schemas/crawler.json, autotransform/schemas/test_author.json, docs/source/autotransform.model.anthropic.rst, docs/source/autotransform.model.rst, requirements.txt, setup.py, src/python/autotransform/config/config.py, src/python/autotransform/config/environment.py, src/python/autotransform/model/anthropic.py, src/python/autotransform/model/openai.py
Adds the Anthropic model and fixes some leftover stuff in the OpenAI model.
=> Add Anthropic Model and Update OpenAI Model
